Surveyy
shaqayq/Survey_form_project pull request #1
Opened 2022-05-02 21:07 UTC by shaqayq

Add file:

1. Index.html
2. index.css
3. Readme
4. MIT.md

2022-05-03 10:57 UTC, shaqayq commented
1. Add linter to analyze source code and catch the syntax errors
2. Change the .css file to style.css or another name that different from .htm filename

2022-05-03 11:43 UTC, shaqayq commented
It's better to add a linter in your project that finds and checks syntax errors .you can find and know more about linter in (https://github.com/microverseinc/linters-config)

2022-05-03 11:51 UTC, shaqayq commented
You need to change the .css file name to a specific name so that you can know better your files and can manage each part. because if you check the code again after a while, the file name will be understandable to you, and if someone else uses your code, it will easily understand which part of each file it belongs to.

2022-05-03 12:08 UTC, m05e5 requested changes
Hi @shaqayq, 

Good job so far. I really like what you did!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

Hi great job with your review. 
-  [ ] Please as part of the requirements, you are supposed to provide at least 2 inline comments. You can do that by going to "files changed", and selecting the part of the code that can be improved 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 12:08 UTC, m05e5 commented on index.html
> +
Example.
 Great job.
- I suggest removing unnecessary empty lines of code. It's better to keep your code clean and professional.

2022-05-03 12:50 UTC, sja-thedude commented on index.html
> +    <title>Document</title>
- [ ] Kindly name your title in a way it is clear and gives an overview of what is in the project.

2022-05-03 12:59 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @shaqayq, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Great job so far

 ## Required Changes ♻️
- [ ] Kindly make sure to add 2 inline comments as suggested by the previous reviewer. I have given examples of how you can write an inline comment below-:

https://user-images.githubusercontent.com/70269507/166457037-d708a288-cf74-4511-97f4-92e2532365ea.mov

https://user-images.githubusercontent.com/70269507/166457009-c4022984-b169-49ad-95ac-0863e36fc25b.mov

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 09:20 UTC, Mre55 requested changes
**Hi @shaqayq,**

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The README is well documented ✅ 

 ## Required Changes ♻️

**[REQUIRED]** As requested by the previous reviewers and also it's [this project requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md#project-requirements) you're supposed to add a minimum of `2 inline` comments you can check under `How to use GitHub features? point 3` [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-use-github-features) how to do that. Or to refer more check [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request).

<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>

## Optional suggestions 🟡 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 20:26 UTC, shaqayq commented
## Required Changes ♻️

Hi @shaqayq 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Great job so far



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 20:39 UTC, shaqayq commented on README.md
> +
You have documented the readme very well. it is advisable to add a few more networking links so that it would be easier for other developers to connect with you.

2022-05-04 20:39 UTC, shaqayq commented on index.html
> +    <title>Document</title>
Your code looks professional. it is advisable to use meaningful titles to increase the SEO performance.

2022-05-04 20:44 UTC, ShahierNashaat approved these changes
Hi @shaqayq , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 21:22 UTC, merged